// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GreenLeaf.Repository.Models;

public partial class Feedback
{
    public int FeedbackId { get; set; }

    public string Content { get; set; }

    public string AttachedFile { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public bool Status { get; set; }

    public decimal Rate { get; set; }

    public int? UserId { get; set; }

    public int? ProductId { get; set; }

    public virtual Product Product { get; set; }

    public virtual User User { get; set; }
}