// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GreenLeaf.Repository.Models;

public partial class OcopCompany
{
    public int CompanyId { get; set; }

    public string CompanyName { get; set; }

    public string Description { get; set; }

    public string Address { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public string CertificationImage { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public int? UserId { get; set; }

    public int? CompanyCategoryId { get; set; }

    public virtual OcopCompanyCategory CompanyCategory { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<ProductExchange> ProductExchanges { get; set; } = new List<ProductExchange>();

    public virtual ICollection<Warehouse> Warehouses { get; set; } = new List<Warehouse>();
}