// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GreenLeaf.Repository.Models;

public partial class ProductExchange
{
    public int ExchangeId { get; set; }

    public DateTime? Date { get; set; }

    public int? UserId { get; set; }

    public int? WarehouseId { get; set; }

    public int? CompanyId { get; set; }

    public virtual OcopCompany Company { get; set; }

    public virtual ICollection<ProductExchangeDetail> ProductExchangeDetails { get; set; } = new List<ProductExchangeDetail>();

    public virtual User User { get; set; }

    public virtual Warehouse Warehouse { get; set; }
}