// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GreenLeaf.Repository.Models;

public partial class ProductExchangeDetail
{
    public int ExchangeDetailId { get; set; }

    public decimal Price { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public int Quantity { get; set; }

    public string Note { get; set; }

    public int? ExchangeId { get; set; }

    public int? ProductId { get; set; }

    public virtual ProductExchange Exchange { get; set; }

    public virtual Product Product { get; set; }
}