// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GreenLeaf.Repository.Models;

public partial class ProductCategory
{
    public int CategoryId { get; set; }

    public string Name { get; set; }

    public int? OcopCompanyId { get; set; }

    public virtual OcopCompany OcopCompany { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}