// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GreenLeaf.Repository.Models;

public partial class Warehouse
{
    public int WarehouseId { get; set; }

    public int Quantity { get; set; }

    public bool Status { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public decimal Price { get; set; }

    public int? ProductId { get; set; }

    public int? CompanyId { get; set; }

    public int? StaffId { get; set; }

    public virtual OcopCompany Company { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual Product Product { get; set; }

    public virtual ICollection<ProductExchange> ProductExchanges { get; set; } = new List<ProductExchange>();

    public virtual StaffId Staff { get; set; }
}